import { BestsellersSlice } from './prismicio-types.d';
// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *app_settings → Navigation*
 */
export interface AppSettingsDocumentDataNavigationItem {
  /**
   * Link field in *app_settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *app_settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *app_settings → Haircontainer*
 */
export interface AppSettingsDocumentDataHaircontainerItem {
  /**
   * Hairimage field in *app_settings → Haircontainer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[].hairimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hairimage: prismic.ImageField<never>;

  /**
   * Hairname field in *app_settings → Haircontainer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[].hairname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairname: prismic.KeyTextField;

  /**
   * Hairdescription field in *app_settings → Haircontainer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[].hairdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairdescription: prismic.KeyTextField;

  /**
   * Hairprize field in *app_settings → Haircontainer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[].hairprize
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairprize: prismic.KeyTextField;
}

/**
 * Content for app_settings documents
 */
interface AppSettingsDocumentData {
  /**
   * Site Title field in *app_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *app_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *app_settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<
    Simplify<AppSettingsDocumentDataNavigationItem>
  >;

  /**
   * Carticon field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.carticon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carticon: prismic.ImageField<never>;

  /**
   * Logo field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menuicon field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.menuicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  menuicon: prismic.ImageField<never>;

  /**
   * Exiticon field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.exiticon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  exiticon: prismic.ImageField<never>;

  /**
   * Haircontainer field in *app_settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  haircontainer: prismic.GroupField<
    Simplify<AppSettingsDocumentDataHaircontainerItem>
  >;
}

/**
 * app_settings document from Prismic
 *
 * - **API ID**: `app_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AppSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithout<
    Simplify<AppSettingsDocumentData>,
    "app_settings",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = BestsellersSlice | HeroSlice | WhychooseusSlice;

/**
 * Content for Homepage documents
 */
interface HomePageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  BestsellersSlice
  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithout<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

export type AllDocumentTypes = AppSettingsDocument | HomePageDocument;

/**
 * Primary content in *Bestsellers → Primary*
 */
export interface BestsellersSliceDefaultPrimary {
  /**
   * Header field in *Bestsellers → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;
}

/**
 * Primary content in *Bestsellers → Items*
 */
export interface BestsellersSliceDefaultItem {
  /**
   * Hairimage field in *Bestsellers → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.items[].hairimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hairimage: prismic.ImageField<never>;

  /**
   * Hairtitle field in *Bestsellers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.items[].hairtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairtitle: prismic.KeyTextField;

  /**
   * Hairdescription field in *Bestsellers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.items[].hairdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairdescription: prismic.KeyTextField;

  slice

  /**
   * Hairprize field in *Bestsellers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.items[].hairprize
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairprize: prismic.KeyTextField;
}

/**
 * Default variation for Bestsellers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BestsellersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BestsellersSliceDefaultPrimary>,
  Simplify<BestsellersSliceDefaultItem>
>;

/**
 * Slice variation for *Bestsellers*
 */
type BestsellersSliceVariation = BestsellersSliceDefault;

/**
 * Bestsellers Shared Slice
 *
 * - **API ID**: `bestsellers`
 * - **Description**: Bestsellers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BestsellersSlice = prismic.SharedSlice<
  "bestsellers",
  BestsellersSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Header1 field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.header1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header1: prismic.RichTextField;

  /**
   * Header2 field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.header2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header2: prismic.RichTextField;

  /**
   * HeroImage field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;
}



/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;






/**
 * Primary content in *Whychooseus → Primary*
 */
export interface WhychooseusSliceDefaultPrimary {
  /**
   * Header field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.header1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.KeyTextField;

  /**
   * writeup field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.header2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  writeup: prismic.KeyTextField;


}



/**
 * Default variation for Whychooseus Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhychooseusSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhychooseusSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Whychooseus*
 */
type WhychooseusSliceVariation = WhychooseusSliceDefault;

/**
 * Whychooseus Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhychooseusSlice = prismic.SharedSlice<"whychooseus", WhychooseusSliceVariation>;


declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AppSettingsDocument,
      AppSettingsDocumentData,
      AppSettingsDocumentDataNavigationItem,
      AppSettingsDocumentDataHaircontainerItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BestsellersSlice,
      BestsellersSliceDefaultPrimary,
      BestsellersSliceDefaultItem,
      BestsellersSliceVariation,
      BestsellersSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      WhychooseusSlice,
      WhychooseusSliceDefaultPrimary,
      WhychooseusSliceVariation,
      WhychooseusSliceDefault,
    };
  }
}
