// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *app_settings → Navigation*
 */
export interface AppSettingsDocumentDataNavigationItem {
  /**
   * Link field in *app_settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *app_settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *app_settings → Haircontainer*
 */
export interface AppSettingsDocumentDataHaircontainerItem {
  /**
   * Hairimage field in *app_settings → Haircontainer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[].hairimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hairimage: prismic.ImageField<never>;

  /**
   * Hairname field in *app_settings → Haircontainer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[].hairname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairname: prismic.KeyTextField;

  /**
   * Hairdescription field in *app_settings → Haircontainer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[].hairdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairdescription: prismic.KeyTextField;

  /**
   * Hairprize field in *app_settings → Haircontainer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[].hairprize
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairprize: prismic.KeyTextField;
}

/**
 * Content for app_settings documents
 */
interface AppSettingsDocumentData {
  /**
   * Site Title field in *app_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *app_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *app_settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<
    Simplify<AppSettingsDocumentDataNavigationItem>
  >;

  /**
   * Carticon field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.carticon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carticon: prismic.ImageField<never>;

  /**
   * Logo field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menuicon field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.menuicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  menuicon: prismic.ImageField<never>;

  /**
   * Exiticon field in *app_settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.exiticon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  exiticon: prismic.ImageField<never>;

  /**
   * Haircontainer field in *app_settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.haircontainer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  haircontainer: prismic.GroupField<
    Simplify<AppSettingsDocumentDataHaircontainerItem>
  >;

  /**
   * Address field in *app_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Refundpolicy field in *app_settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.refundpolicy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  refundpolicy: prismic.LinkField;

  /**
   * Shippingpolicy field in *app_settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.shippingpolicy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  shippingpolicy: prismic.LinkField;

  /**
   * Termsandconditions field in *app_settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app_settings.termsandconditions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  termsandconditions: prismic.LinkField;
}

/**
 * app_settings document from Prismic
 *
 * - **API ID**: `app_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AppSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AppSettingsDocumentData>,
    "app_settings",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | DeliverysectionSlice
  | TestimonialsSlice
  | WhychooseusSlice
  | BestsellersSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomePageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type PageDocumentDataSlicesSlice = BestsellersSlice | WhychooseusSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | AppSettingsDocument
  | HomePageDocument
  | PageDocument;

/**
 * Primary content in *Bestsellers → Default → Primary*
 */
export interface BestsellersSliceDefaultPrimary {
  /**
   * Header field in *Bestsellers → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;
}

/**
 * Primary content in *Bestsellers → Items*
 */
export interface BestsellersSliceDefaultItem {
  /**
   * Hairimage field in *Bestsellers → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.items[].hairimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hairimage: prismic.ImageField<never>;

  /**
   * Hairtitle field in *Bestsellers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.items[].hairtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairtitle: prismic.KeyTextField;

  /**
   * Hairdescription field in *Bestsellers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.items[].hairdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairdescription: prismic.KeyTextField;

  /**
   * Hairprize field in *Bestsellers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bestsellers.items[].hairprize
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hairprize: prismic.KeyTextField;
}

/**
 * Default variation for Bestsellers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BestsellersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BestsellersSliceDefaultPrimary>,
  Simplify<BestsellersSliceDefaultItem>
>;

/**
 * Slice variation for *Bestsellers*
 */
type BestsellersSliceVariation = BestsellersSliceDefault;

/**
 * Bestsellers Shared Slice
 *
 * - **API ID**: `bestsellers`
 * - **Description**: Bestsellers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BestsellersSlice = prismic.SharedSlice<
  "bestsellers",
  BestsellersSliceVariation
>;

/**
 * Primary content in *Deliverysection → Default → Primary*
 */
export interface DeliverysectionSliceDefaultPrimary {
  /**
   * Writeup field in *Deliverysection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deliverysection.default.primary.writeup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup: prismic.KeyTextField;
}

/**
 * Default variation for Deliverysection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DeliverysectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DeliverysectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Deliverysection*
 */
type DeliverysectionSliceVariation = DeliverysectionSliceDefault;

/**
 * Deliverysection Shared Slice
 *
 * - **API ID**: `deliverysection`
 * - **Description**: Deliverysection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DeliverysectionSlice = prismic.SharedSlice<
  "deliverysection",
  DeliverysectionSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Header1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.header1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header1: prismic.RichTextField;

  /**
   * Header2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.header2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header2: prismic.RichTextField;

  /**
   * HeroImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Testimony field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].testimony
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimony: prismic.KeyTextField;

  /**
   * Testifierimage field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].testifierimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testifierimage: prismic.ImageField<never>;

  /**
   * Testifiername field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].testifiername
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testifiername: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *Whychooseus → Aboutus → Primary*
 */
export interface WhychooseusSliceDefaultPrimary {
  /**
   * Header field in *Whychooseus → Aboutus → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whychooseus.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Writeup field in *Whychooseus → Aboutus → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whychooseus.default.primary.writeup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup: prismic.KeyTextField;
}

/**
 * Aboutus variation for Whychooseus Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhychooseusSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhychooseusSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Whychooseus*
 */
type WhychooseusSliceVariation = WhychooseusSliceDefault;

/**
 * Whychooseus Shared Slice
 *
 * - **API ID**: `whychooseus`
 * - **Description**: Whychooseus
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhychooseusSlice = prismic.SharedSlice<
  "whychooseus",
  WhychooseusSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AppSettingsDocument,
      AppSettingsDocumentData,
      AppSettingsDocumentDataNavigationItem,
      AppSettingsDocumentDataHaircontainerItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BestsellersSlice,
      BestsellersSliceDefaultPrimary,
      BestsellersSliceDefaultItem,
      BestsellersSliceVariation,
      BestsellersSliceDefault,
      DeliverysectionSlice,
      DeliverysectionSliceDefaultPrimary,
      DeliverysectionSliceVariation,
      DeliverysectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      WhychooseusSlice,
      WhychooseusSliceDefaultPrimary,
      WhychooseusSliceVariation,
      WhychooseusSliceDefault,
    };
  }
}
