// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bestsellers: dynamic(() => import("./Bestsellers")),
  deliverysection: dynamic(() => import("./Deliverysection")),
  extrapage: dynamic(() => import("./Extrapage")),
  hero: dynamic(() => import("./Hero")),
  testimonials: dynamic(() => import("./Testimonials")),
  whychooseus: dynamic(() => import("./Whychooseus")),
};
